config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  resources :charges, only: [:new, :create]

  root 'welcome#index'

  get 'welcome/about'

  post '/downgrade-account', to:'charges#downgrade', as: :downgrade_account

  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :wiki_id, message: 'Collaborator has already been added.'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :shared_wikis, through: :collaborators, source: :wiki

  after_initialize :init

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: [:standard, :premium, :admin]

  def init
    self.role||= :standard
  end

  def upgrade
    update_attribute(:role, :premium )
  end

  def downgrade
    update_attribute(:role, :standard)
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :shared_users, through: :collaborators, source: :user
  
  after_initialize :init

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true

  def init
    self.private||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:index]
  # before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Creates a Stripe Customer object, for associating
    # with the charge

    customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in your app
        amount: amount_default,
        description: "BigMoney Membership - #{current_user.email}",
        currency: 'usd'
    )

    if charge['paid'] == true
      current_user.upgrade
    end

    flash[:notice] = "Thanks for your payment, #{current_user.email}! Your account has been upgraded to Premium."
    redirect_to root_path # or wherever

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: "BigMoney Membership - #{current_user.email}",
        amount: amount_default
    }
  end

  def downgrade
    current_user.update_attribute(:role, :standard)
    current_user.wikis.where(private: true).update_all(private: false)
    flash[:notice] = "Your account has been downgraded to standard. All of your private wikis have been made public."
    redirect_to root_path
  end

  private

  def amount_default
    15_00
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki


  def new
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator added to this wiki."
      redirect_to request.referrer || wikis_path
    else
      flash.now[:alert] = "Unable to add collaborator."
      redirect_to request.referrer || wikis_path
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from this wiki."
      redirect_to request.referrer || wikis_path
    else
      flash.now[:alert] = "Unable to remove collaborator from this wiki."
      redirect_to request.referrer || wikis_path
    end
  end

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  after_action :verify_authorized

  def index
    authorize Wiki
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    authorize Wiki
    @wiki = Wiki.new
  end

  def create
    authorize Wiki
    @wiki = current_user.wikis.build(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.where.not(role: 'admin')
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end

  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(policy(Wiki).permitted_attributes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <%= form_tag charges_path do %>
          <h4>Click the button to upgrade to a Premium account!</h4>
          <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"></script>
      <% end %>
    </div>
  </div>
</div>

app/views/collaborators/_add_collaborator.html.erb
<div class="container">
    <h1>Add Collaborators</h1>

  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <table class="table table-striped align-middle">
        <% @users.each do |user| %>
            <tr class="align-middle">
              <td> <%= user.email %> </td>
                  <% if wiki.collaborators.pluck(:user_id).include? user.id %>
                      <td> </td>
                      <td> 
                          <%= link_to "Remove Access", "/wikis/#{wiki.id}/collaborators/#{wiki.collaborators.where(user_id: user.id).first.id}", class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure you want to remove this collaborator?'} %> 
                      </td>

                  <% else %>
                      <td>
                          <%= link_to "Give Access", new_wiki_collaborator_url(wiki, user_id: user.id), class: 'btn btn-success' %>
                      </td>
                      <td> </td>


                  <% end %>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<%= link_to "Remove Access", '/wikis/#{wiki}/collaborators/#{user.id}', controller: 'collaborators', action: 'destroy', class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure you want to remove this collaborator?'} %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
</head>

<body>
<div class="container">
  <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong>
      <ul class="nav nav-tabs navbar-right">
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
        <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
  <% else %>
      <ul class="nav nav-tabs navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
  <% end %>
        <li><%= link_to "Wikis", wikis_path, :class => 'navbar-link' %></li>
  </ul>
  <div class="clearfix"></div>

  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
  <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>

  <% end %>

<% if current_user && current_user.role == 'standard' && controller.controller_name != "charges"%>
<p class="text-center">You are using a free account and will not be able to create private wikis.
  <%= link_to 'Upgrade', new_charge_path, class: 'btn btn-success' %>
</p>
<% end %>
</div>

<%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Blocipedia: Social, Markdown Wikis</h1>


  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <div class="jumbotron text-center">
        <h2>Create and share Markdown Wikis</h2>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-push-2 text-center">
      <p>Create as many public wikis as you want!</p>
      <a href="#" class="thumbnail">
        <%= image_tag "public.png", alt:"public icon"%>
        <h3>Free Plan</h3>
      </a>
    </div>

    <div class="col-md-4 col-md-push-2 text-center">
      <p>Create private wikis!</p>
      <a href="#" class="thumbnail">
        <%= image_tag "private.jpeg", alt:"public icon"%>
        <h3>Premium Plan</h3>
      </a>
    </div>

  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
    <% if wiki.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
          <ul>
            <% wiki.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= form_group_tag(wiki.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    <% end %>

    <%= form_group_tag(wiki.errors[:body]) do %>
        <%= f.label :body %>
        <p>You can use markdown syntax to style your wiki. Refer to the <%= link_to 'markdown documentation', 'https://daringfireball.net/projects/markdown/syntax' %> for more information.</p>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    <% end %>

    <% if policy(wiki).permitted_attributes.include? :private %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki_post_path(wiki) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %> <br>
    </small>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>No swearing</li>
      <li>Defamatory or pejorative remarks will be removed</li>
      <li>Good punctuation and grammar are key</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>

  <%=
  if current_user == @wiki.user
      render partial: 'collaborators/add_collaborator', locals: {wiki: @wiki, users: @users}
    end
  %>

</div>

app/views/wikis/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <h1>New Wiki</h1>
      <p>Guidelines for wikis</p>
      <ul>
        <li>No swearing</li>
        <li>Defamatory or pejorative remarks will be removed</li>
        <li>Good punctuation and grammar are key</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= render partial: 'form', locals: {wiki: @wiki} %>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <div>
    <h1>
      <%= @wiki.title %>
      <small>
        submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
      </small>
    </h1>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <p><%= markdown(@wiki.body) %></p>
    </div>

  </div>

  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <%= link_to 'Edit', edit_wiki_path(@wiki), {class: 'btn btn-success'} %>
    </div>

  </div>
</div>